name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue is being marked as stale due to a long period of inactivity"
          stale-pr-message: "This PR is being marked as stale due to a long period of inactivity"
          stale-issue-label: "no-issue-activity"
          stale-pr-label: "no-pr-activity"
